### ISSUE TITLE
installation: amend DB configuration

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/claimstore#46]
We may want to change the way how the app is configured (and initialised) WRT database.  For example, the documentation building step at the RTFD leads to troubles with uninitialised `SQLALCHEMY_DATABASE_URI`:

```
Running Sphinx v1.3.1
making output directory...
loading translations [en]... done
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [ 16%] api
reading sources... [ 33%] description
reading sources... [ 50%] design
reading sources... [ 66%] developers
reading sources... [ 83%] index
reading sources... [100%] releases

/home/docs/checkouts/readthedocs.org/user_builds/claimstore/checkouts/latest/docs/api.rst:93: WARNING: autodoc: failed to import module 'claimstore.wsgi'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/claimstore/envs/latest/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claimstore/checkouts/latest/claimstore/wsgi.py", line 27, in <module>
    application = create_app()
  File "/home/docs/checkouts/readthedocs.org/user_builds/claimstore/checkouts/latest/claimstore/app.py", line 45, in create_app
    app.config.from_object('config')
  File "/home/docs/checkouts/readthedocs.org/user_builds/claimstore/envs/latest/local/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claimstore/envs/latest/local/lib/python3.4/site-packages/Werkzeug-0.10.4-py3.4.egg/werkzeug/utils.py", line 412, in import_string
    __import__(import_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/claimstore/checkouts/latest/config.py", line 36, in <module>
    "SQLALCHEMY_DATABASE_URI".')
Exception: Please, define the environment variable         "SQLALCHEMY_DATABASE_URI".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 16%] api
writing output... [ 33%] description
writing output... [ 50%] design
writing output... [ 66%] developers
writing output... [ 83%] index
writing output... [100%] releases

generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/user_builds/claimstore/checkouts/latest/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.
Copying readthedocs-dynamic-include.js_t... done
Copying readthedocs-data.js_t... done
```

See also #22.

**Comment by tiborsimko** [comment]
Works in the current `master` branch, closing the ticket.
